# -*- coding: utf-8 -*-
"""Student_Performance_Predictor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13HhqraZxifl8lfbMZ-BTUyz-irW6ON37
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LinearRegression

from sklearn.tree import DecisionTreeRegressor

from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, r2_score

df = pd.read_csv("/content/StudentPerformanceFactors.csv")

df.head()

df.shape

df.isnull().sum()

df.info()

df.describe()

df.fillna(df.mean(numeric_only=True), inplace=True)

for col in df.select_dtypes(include='object'):
    df[col].fillna(df[col].mode()[0], inplace=True)

print(df.select_dtypes(include='object').columns)

le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

import seaborn as sns

plt.figure(figsize=(12,8))

sns.heatmap(
    df.corr(),
    annot=True,
    cmap='coolwarm'
)

plt.show()

plt.scatter(
    df["Attendance"],
    df["Exam_Score"]
)

plt.xlabel("Attendance")

plt.ylabel("Exam Score")

plt.show()

X = df.drop("Exam_Score", axis=1)

y = df["Exam_Score"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

lr = LinearRegression()

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

print(
    "MAE:",
    mean_absolute_error(y_test, lr_pred)
)

print(
    "R²:",
    r2_score(y_test, lr_pred)
)

dt = DecisionTreeRegressor(
    random_state=42
)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

print(
    mean_absolute_error(
        y_test,
        dt_pred
    )
)

print(
    r2_score(
        y_test,
        dt_pred
    )
)

rf = RandomForestRegressor(
    random_state=42
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

print(
    mean_absolute_error(
        y_test,
        rf_pred
    )
)

print(
    r2_score(
        y_test,
        rf_pred
    )
)

"""Compare the models
Model with low MAE and high R^2 is best

"""

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance.sort_values(
    by="Importance",
    ascending=False,
    inplace=True
)

print(importance)

"""Q: Why did you choose Linear Regression even though Random Forest is more advanced?

Answer:

"I evaluated multiple models using MAE and R² score. Linear Regression achieved the lowest MAE and highest R² score on this dataset, indicating better generalization performance. Therefore, I selected it as the final model."


"""